var fs = require('fs');
var request = require('request');
var xpath = require('xpath');
var parse5 = require('parse5');
var xmlser = require('xmlserializer');
var dom = require('xmldom').DOMParser;
var uuid = require('node-uuid');
var phantom = require('phantom');
var knox = require('knox');
var mkdirp = require('mkdirp');
Config = require('nconf');
Config.argv()
     .env()
     .file({ file: 'config.json' });
var AWS_KEY = process.env.AWS_KEY || Config.get("AWS_KEY")
  , AWS_SECRET = process.env.AWS_SECRET || Config.get("AWS_SECRET")
  , AWS_S3BUCKET = process.env.AWS_S3BUCKET || Config.get("AWS_S3BUCKET");



var findLinkInLikeToBuy = function(instaId, mediaId, cb){
	phantom.create(function (ph) {
	  ph.createPage(function (page) {
	    page.open("http://like2b.uy/"+instaId, function (status) {
	    	if(status == 'success'){
				page.evaluate(function () { return document.documentElement.innerHTML; }, function (result) {
					try {
						var parser = new parse5.Parser();
					    var document = parser.parse(result.toString());
					    var xhtml = xmlser.serializeToString(document);
					    var doc = new dom().parseFromString(xhtml);
						var select = xpath.useNamespaces({"x": "http://www.w3.org/1999/xhtml"});
					    var nodes = select("//x:product-card[@item-identifier='"+mediaId+"']/@destination-url", doc);
					    if (nodes.length == 0 ){
				    		cb(null);
					    }
					    cb(nodes[0].nodeValue);
					}
					catch(exception){
			    		cb(null);
					}
					finally {
				        ph.exit();
					}
			    });
	    	} else {
	    		cb(null);
	    	}
	    });
	  });
	});
}

var getMobileScreenShot = function(url, cb){
	mkdirp('/tmp', function(err) { 
		if (err){
			cb(null);
			return;
		}
		var fileName = uuid.v1()+'.png';
		request('http://ec2-54-68-31-204.us-west-2.compute.amazonaws.com/?url='+encodeURIComponent(url)+'&width=320&clipRect=%7B%22top%22%3A300%2C%22left%22%3A0%2C%22width%22%3A320%2C%22height%22%3A320%7D&userAgent=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+5_0+like+Mac+OS+X%29+AppleWebKit%2F534.46+%28KHTML%2C+like+Gecko%29+Version%2F5.1+Mobile%2F9A334+Safari%2F7534.48.3')
			.on('error', function(err) {
			    console.log(err)
			    cb(null);
			})
			.on('end', function() {
				var client = knox.createClient({
				    key: AWS_KEY
				  , secret: AWS_SECRET
				  , bucket: AWS_S3BUCKET
				});
				var req = client.putFile('/tmp/'+fileName, '/autoGenerated/'+fileName, function(err, res){
				  if (!err){
					  cb(res.req.url);
				  } else {
				  	console.log('not saved: %s', err);
				  	cb(null);
				  }
				  fs.unlink('/tmp/'+fileName, function (err) {
					if (err){
						console.log('couldnt delete file locally');
						cb(null);
					} 
				  });
				  res && res.resume();
				});
			})
			.pipe(fs.createWriteStream('/tmp/'+fileName));
	});
}

exports.findLinkInLikeToBuy = findLinkInLikeToBuy;
exports.getMobileScreenShot = getMobileScreenShot;


findLinkInLikeToBuy('victoriassecret','942118557298873693_3416684',function(result){
	console.log(result);
	getMobileScreenShot(result);
});